### ISSUE TITLE
yolov5版本问题

### ISSUE THREAD

**Issue by Gloria-40** [ash-ali/obj-detection#1]
这个不能支持最新版本的yolov5吗？怎么修改代码支持最新版本的yolov5？

**Comment by Gloria-40** [comment]
问一下博主用的是3.0版本的yolov5还是3.1的？

**Comment by linjie98** [comment]
> 问一下博主用的是3.0版本的yolov5还是3.1的？

你好，应该是3.1版本，目前还未尝试最新版本哈
