### ISSUE TITLE
重启程序出现错误！

### ISSUE THREAD

**Issue by wwj1980** [ash-ali/obj-detection#2]
使用网页摄像头后，停止运行，在启动后，出现：Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from 'C:\\Users\\wwj_e\\.conda\\envs\\flash\\lib\\site-packages\\torch\\nn\\modules\\activation.py'>。
不知道如何解决？请指教。

**Comment by linjie98** [comment]
尝试把SILU类代码粘贴到activation文件下
